#!/bin/sh

# Name: Install
# Purpose: install script for the femover product

# remember the top-level directory

cd `dirname $0`
TOP=`pwd`

# if no Configuration file, bail out

if [ ! -f "${TOP}/Configuration" ]; then
	echo "Missing Configuration file"
	exit 1
fi

# source the Configuration file

. "${TOP}/Configuration"
echo "Sourced Configuration file"

# add/update links to config.py library

CONFIG=${TOP}/lib/python/config.py

for dir in gather control schema postprocess
do
	if [ -h "${TOP}/${dir}/config.py" ]; then
		rm "${TOP}/${dir}/config.py"
	fi
	if [ -f "${TOP}/${dir}/config.pyc" ]; then
		rm "${TOP}/${dir}/config.pyc"
	fi
	ln -s "${CONFIG}" "${TOP}/${dir}/config.py"
	echo "Created symlink: ${TOP}/${dir}/config.py"
done

# create a symlink to the Configuration file from the control directory
# because it is needed by scripts in that directory
cd ${TOP}/control
rm -f Configuration
ln -s ../Configuration Configuration

# back to top level...
cd "${TOP}"

# if we don't have a data and a logs directory, make them

if [ ! -d ${DATA_DIR} ]; then
	mkdir -p ${DATA_DIR}
	echo "Created data directory: ${DATA_DIR}"
fi

if [ ! -d ${LOG_DIR} ]; then
	mkdir ${LOG_DIR}
	echo "Created log directory: ${LOG_DIR}"
fi

# update permissions on gatherers and controllers

chmod ug+x "${TOP}/gather/"*Gatherer.py "${TOP}/control/"*
echo "Granted execute permissions for gatheres and control scripts"

echo "Finished"
