#!/bin/sh

# Name: Install
# Purpose: install script for the femover product

# remember the top-level directory

cd `dirname $0`
TOP=`pwd`

# if no Configuration file, bail out

if [ ! -f "${TOP}/Configuration" ]; then
	echo "Missing Configuration file"
	exit 1
fi

# source the Configuration file

. "${TOP}/Configuration"
echo "Sourced Configuration file"

# add/update links to the Python executable (for Python 3.7)

DIRS="control gather lib/python postprocess schema testdata unittest/gatherer unittest"
for DIR in ${DIRS}
do
	if [ -h ${DIR}/python ]; then
		rm ${DIR}/python
	fi
	ln -s ${PYTHON} ${DIR}/python
	echo "Added link from ${DIR}/python to ${PYTHON}"
done

# add/update links to config.py library

CONFIG=${TOP}/lib/python/config.py

for dir in gather control schema postprocess
do
	if [ -h "${TOP}/${dir}/config.py" ]; then
		rm "${TOP}/${dir}/config.py"
	fi
	if [ -f "${TOP}/${dir}/config.pyc" ]; then
		rm "${TOP}/${dir}/config.pyc"
	fi
	ln -s "${CONFIG}" "${TOP}/${dir}/config.py"
	echo "Created symlink: ${TOP}/${dir}/config.py"
done

# create a symlink to the Configuration file from the control directory
# because it is needed by scripts in that directory
cd ${TOP}/control
rm -f Configuration
ln -s ../Configuration Configuration

# back to top level...
cd "${TOP}"

# if we don't have a data, cache and a logs directory, make them

if [ ! -d ${DATA_DIR} ]; then
	mkdir -p ${DATA_DIR}
	echo "Created data directory: ${DATA_DIR}"
fi

if [ ! -d ${CACHE_DIR} ]; then
	mkdir -p ${CACHE_DIR}
	echo "Created cache directory: ${CACHE_DIR}"
fi

if [ ! -d ${LOG_DIR} ]; then
	mkdir ${LOG_DIR}
	echo "Created log directory: ${LOG_DIR}"
fi

# update permissions on gatherers and controllers

chmod ug+x "${TOP}/gather/"*Gatherer.py "${TOP}/control/"*.py "${TOP}/control"/*.sh
echo "Granted execute permissions for gatherers and control scripts"

echo "Finished"
